### ISSUE TITLE
Implement search through the file storage feature

### ISSUE THREAD

**Issue by AlfPacino** [repetantil/courses-file-storage#10]
On the main page Web File Explorer should be added search input box.
User, by typing his search key words and pressing "Search", is redirected to the same main page of Web File Explorer but now it contains only files/folders that match his request.

- Implement gui
- Implement logic (search engine)

**Comment by repetantil** [comment]
Please add dev plan with technical description

**Comment by AlfPacino** [comment]
Add action to home conroller called "Search" it takes string as a parameter and returns to view search result:
        [HttpGet]
        public ActionResult Search(string SearchRequest)
        {
            var searchStr = Request["Search"];
            var Files = new List<File>();
            foreach (var file in db.Files)
            {
                if (file.Name.Contains(searchStr))
                {
                    Files.Add(file);
                }
            }
            ViewBag.Files = Files;
            return View("Index");
        }

In view: search form:
        @using (Html.BeginForm("Search", "Home", FormMethod.Get))
        {
            @Html.TextBox("Search")
            <input type="submit" value="Search" class="btn-success" />
        }
