### ISSUE TITLE
Create a download page.

### ISSUE THREAD

**Issue by DoctorChaOs96** [repetantil/courses-file-storage#5]
We must implement: 
- downloading a single file;
- downloading few files;
- downloading a single folder or few folders;

**Comment by repetantil** [comment]
1) "drag and drop feature" is more about upload rather than download.
2) Please create separate tickets for all types of download

**Comment by DoctorChaOs96** [comment]
## #5 Ticke №1: downloading a single file
1. Implement the controller with name DownloadController.
2. The controller must receive the FileID of the downloading file.
3. After receiving the FileID, the access to the file by this user is checked.
4. If the user has access then he gets the file.
