### ISSUE TITLE
Create an upload page.

### ISSUE THREAD

**Issue by DoctorChaOs96** [repetantil/courses-file-storage#6]
We must implement: 
- unloading a single file;
- uploading few files;
- drag and drop feature;

**Comment by repetantil** [comment]
Please add dev plan with technical description

**Comment by DoctorChaOs96** [comment]
## Ticket №1: unloading a single file.

1. Create the class with name "File" in the Models folder:
```
class File
        {
            public int ID { get; set; }
            [Required]
            [StringLength(255)]
            public string FileName { get; set; }
            [Required]
            public string Path { get; set; } // path to file on the server 
            public string Link { get; set; } // link to get the file by reference

        }
```
2.  Implement a HttpPost controller: 
`Controllers.HomeController.Upload` <- `public ViewResult Upload(HttpPostedFileBase   ##upload)`
After saving the file to the server, put the file-information in the DataTable.

3. Create a view for the UploadController: Views -> Upload -> UploadPage.
This view must have buttons: "Choose file", "Upload".

**Comment by DoctorChaOs96** [comment]
## Ticket №1: unloading a single file.

1. Create the class with name "File" in the Models folder:
```
        class File
        {
            public int ID { get; set; }
            [Required]
            [StringLength(255)]
            public string FileName { get; set; }
            [Required]
            public string Path { get; set; } // path to file on the server 
            public string Link { get; set; } // link to get the file by reference

        }
```
2. Implement a `HttpPost` controller:
`Controllers.HomeController.Upload` <- `public ViewResult Upload(HttpPostedFileBase ##upload)`
After saving the file to the server, put the file-information in the DataTable.

3. Create a view for the UploadController: Views -> Upload -> UploadPage.
This view must have buttons: "Choose file", "Upload".

**Comment by DoctorChaOs96** [comment]
## #6: Ticket №2: uploading a few file.
1. Change controller parameter:
 `Upload(HttpPostedFileBase upload)`  ->  `Upload(HttpPostedFileBase[] files)`
2. Set up processing of the files array and implemente adding file information to the DB.
![upload](https://cloud.githubusercontent.com/assets/26484855/24473415/dcc7a3f2-14d1-11e7-8c17-36c2f3189de3.jpg)

**Comment by DoctorChaOs96** [comment]
## #6: Ticket №3: implemant drag & drop feature.
1. Implementation drag and droup through `using Dropzonejs `
Source:
[http://www.dropzonejs.com/#create-dropzones-programmatically](url)
2. The upload page must have the button "Select File" and Drag & Drop field.
3. After downloading the user should receive a message about the result of the download.
